// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnihscqeyeouprepxwte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduaWhzY3FleWVvdXByZXB4d3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzgzMjAsImV4cCI6MjA3MTM1NDMyMH0.i1-dD4opTkgBryewpWFSNfezrzsILOKLooxG_r_7-XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});